// Generated by CoffeeScript 1.3.3
(function() {
  var $;

  global.jQuery = require("jquery");

  $ = jQuery;

  require('../src/jquery.isolatepage');

  describe("isolatePage", function() {
    return describe("loadPage", function() {
      it("loads the javascript for a given page", function() {
        var result;
        result = 1;
        $.isolatePage('setPage', "testpage", function() {
          return result = 2;
        });
        $.isolatePage('loadPage', "testpage");
        return expect(result).toEqual(2);
      });
      it("does not load the javascript for different pages", function() {
        var result;
        result = 1;
        $.isolatePage('setPage', "testpage", function() {
          return result = 2;
        });
        $.isolatePage('loadPage', "another");
        return expect(result).toEqual(1);
      });
      return it("takes arrays of different page names", function() {
        var result;
        result = 1;
        $.isolatePage('setPage', ["testpage", "another"], function() {
          return result = 2;
        });
        $.isolatePage('loadPage', "another");
        expect(result).toEqual(2);
        result = 1;
        $.isolatePage('loadPage', "testpage");
        return expect(result).toEqual(2);
      });
    });
  });

}).call(this);
